services:
  epics-base:
    image: ${REGISTRY:-ghcr.io/cnpem}/lnls-alpine-3-epics-7:$TAG
    build:
      context: ../
      dockerfile: musl/Dockerfile
      labels:
        org.opencontainers.image.revision: ${TAG}
        org.opencontainers.image.source: ${SOURCE:-https://github.com/cnpem/epics-in-docker}
        org.opencontainers.image.description: "EPICS base and modules build image for fully static executables"
      args:
        JOBS: ${JOBS:-1}
        ALPINE_VERSION: ${ALPINE_VERSION}
        EPICS_BASE_VERSION: ${EPICS7_BASE_VERSION}
        PVXS_VERSION: ${PVXS_VERSION}
        SEQUENCER_VERSION: ${SEQUENCER_VERSION}
        CALC_VERSION: ${CALC_VERSION}
        ASYN_VERSION: ${ASYN_VERSION}
        MODBUS_VERSION: ${MODBUS_VERSION}
        STREAMDEVICE_VERSION: ${STREAMDEVICE_VERSION}
        BUSY_VERSION: ${BUSY_VERSION}
        AUTOSAVE_VERSION: ${AUTOSAVE_VERSION}
        SSCAN_VERSION: ${SSCAN_VERSION}
        RECCASTER_VERSION: ${RECCASTER_VERSION}
        IPAC_VERSION: ${IPAC_VERSION}
        CAPUTLOG_VERSION: ${CAPUTLOG_VERSION}
        RETOOLS_VERSION: ${RETOOLS_VERSION}
        ETHER_IP_VERSION: ${ETHER_IP_VERSION}
        IOCSTATS_VERSION: ${IOCSTATS_VERSION}
        IPMICOMM_VERSION: ${IPMICOMM_VERSION}
        PYDEVSUP_VERSION: ${PYDEVSUP_VERSION}
        SNMP_VERSION: ${SNMP_VERSION}
        SCALER_VERSION: ${SCALER_VERSION}
        MCA_VERSION: ${MCA_VERSION}
        EPICS_BASE_SHA256: ${EPICS7_BASE_SHA256}
        PVXS_SHA256: ${PVXS_SHA256}
        SEQUENCER_SHA256: ${SEQUENCER_SHA256}
        CALC_SHA256: ${CALC_SHA256}
        ASYN_SHA256: ${ASYN_SHA256}
        MODBUS_SHA256: ${MODBUS_SHA256}
        STREAMDEVICE_SHA256: ${STREAMDEVICE_SHA256}
        BUSY_SHA256: ${BUSY_SHA256}
        AUTOSAVE_SHA256: ${AUTOSAVE_SHA256}
        SSCAN_SHA256: ${SSCAN_SHA256}
        RECCASTER_SHA256: ${RECCASTER_SHA256}
        IPAC_SHA256: ${IPAC_SHA256}
        CAPUTLOG_SHA256: ${CAPUTLOG_SHA256}
        RETOOLS_SHA256: ${RETOOLS_SHA256}
        ETHER_IP_SHA256: ${ETHER_IP_SHA256}
        IOCSTATS_SHA256: ${IOCSTATS_SHA256}
        IPMICOMM_SHA256: ${IPMICOMM_SHA256}
        PYDEVSUP_SHA256: ${PYDEVSUP_SHA256}
        SNMP_SHA256: ${SNMP_SHA256}
        SCALER_SHA256: ${SCALER_SHA256}
        MCA_SHA256: ${MCA_SHA256}
