services:
  twincat_ads:
    image: ghcr.io/cnpem/twincat-ads-epics-ioc:$TAG
    build:
      context: ./
      dockerfile: ../Dockerfile
      target: static-link
      labels:
        org.opencontainers.image.source: https://github.com/cnpem/epics-in-docker
      args:
        IOC_CREATE: 1
        REPONAME: twincatADS
        RUNDIR: /opt/twincatADS/iocBoot/ioctwincatADS
        IOC_DBDS:
          asyn.dbd
          ads.dbd
        IOC_LIBS:
          ads
          asyn
