services:
  epics-base:
    image: ghcr.io/cnpem/epics-base:$TAG
    build:
      context: ./
      dockerfile: ../Dockerfile
      target: no-build
      labels:
        org.opencontainers.image.source: https://github.com/cnpem/epics-in-docker
      args:
        APP_DIRS: /opt/epics/base /opt/epics/modules/pvxs
        RUNDIR: /opt/epics/base/bin/linux-x86_64
        RUNTIME_PACKAGES: libevent-pthreads-2.1-7
        ENTRYPOINT: /usr/bin/bash
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/epics/base/bin/linux-x86_64:/opt/epics/modules/pvxs/bin/linux-x86_64
  epics-base-latest:
    extends: epics-base
    image: ghcr.io/cnpem/epics-base:latest
