services:
  mca:
    image: ghcr.io/cnpem/mca-epics-ioc:$TAG
    build:
      context: ./
      dockerfile: ../Dockerfile
      target: no-build
      labels:
        org.opencontainers.image.source: https://github.com/cnpem/epics-in-docker
      args:
        APP_DIRS: /opt/epics/modules/mca
        RUNDIR: /opt/epics/modules/mca/iocBoot/iocAmptek
        RUNTIME_PACKAGES: libpcap0.8 libnet1 libusb-1.0-0
