services:
  opcua:
    image: ghcr.io/cnpem/opcua-epics-ioc:$TAG
    build:
      context: ./
      dockerfile: ../Dockerfile
      target: dynamic-link
      labels:
        org.opencontainers.image.source: https://github.com/cnpem/epics-in-docker
      args:
        IOC_CREATE: 1
        RUNTIME_PACKAGES: libxml2
        REPONAME: opcua
        RUNDIR: /opt/opcua/iocBoot/iocopcua
        IOC_DBDS:
          opcua.dbd
        IOC_LIBS:
          opcua
