name: Build image
on:
  workflow_call:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      SOURCE: https://github.com/${{ github.repository }}
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - name: Log in to registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push tagged image
        uses: docker/bake-action@v4
        with:
          workdir: ./
          files: docker-compose.yml
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          push: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
