name: Update Release Branch
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  update-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Update release branch
        run: |
          git push origin ${{ github.ref_name }}:release
